version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    ports:
      - "1883:1883"   # unverschl√ºsselt optional
      - "8883:8883"   # TLS
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./data:/mosquitto/data
      - ./certs:/mosquitto/certs
    restart: unless-stopped

